#!/usr/bin/env php
<?php

/*
 * This file is part of the OXID Console package.
 *
 * (c) Eligijus Vitkauskas <eligijusvitkauskas@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require_once 'bootstrap.php';

// OXID Bug: Smarty gets loaded only with oxUtils class
// Invoking autoloader to load oxUtils class so Smarty class
// gets loaded too
class_exists('oxUtils');

/** @var oxConsoleApplication $oConsole */
$oConsole = oxNew('oxConsoleApplication');
$oConsole->run();
