#!/bin/bash -e

# =============================================================================
# Check if all necessary variables are set
# =============================================================================

if [[ -z $OXID_VERSION ]]; then
    echo "OXID_VERSION has not been specified"
    exit 1
fi

# =============================================================================
# Download and and put oxid environment in place
# =============================================================================

mkdir oxid
wget -O - https://github.com/OXID-eSales/oxideshop_ce/archive/v$OXID_VERSION.tar.gz | tar xzf - -C oxid --strip-components 1
