#!/bin/bash

set -e

PROJECTPATH=$(cd $(dirname $0)/..; pwd -P);

# =============================================================================
# Check if all necessary variables are set
# =============================================================================

if [[ -z $MYSQL_DATABASE_NAME ]]; then
    echo "MYSQL_DATABASE_NAME has not been specified"
    exit 2
fi

if [[ -z $MYSQL_USER ]]; then
    echo "MYSQL_USER has not been specified"
    exit 3
fi

# =============================================================================
# Setup MySQL database
# =============================================================================

mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD -e "DROP DATABASE IF EXISTS $MYSQL_DATABASE_NAME"
mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE_NAME"
mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE_NAME < oxid/Setup/Sql/database_schema.sql
mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE_NAME < oxid/Setup/Sql/latin1_to_utf8.sql


# =============================================================================
# Replace configuration values in config.inc.php
#
# Credits: https://github.com/OXID-eSales/oxideshop_ce/blob/v4.9.4/.travis.yml#L43
# =============================================================================

sed 's|<dbHost_ce>|127.0.0.1|; s|<dbName_ce>|'$MYSQL_DATABASE_NAME'|; s|<dbUser_ce>|'$MYSQL_USER'|; s|<dbPwd_ce>|'$MYSQL_PASSWORD'|; s|<sShopURL_ce>|http://127.0.0.1|; s|<sShopDir_ce>|'$PROJECTPATH'/oxid|; s|<sCompileDir_ce>|'$PROJECTPATH'/oxid/tmp|; s|<iUtfMode>|1|' oxid/config.inc.php.dist > oxid/config.inc.php
