#!/bin/bash -e

OXID_SOURCE_PATH="`pwd`/oxid/source"

# =============================================================================
# Check if all necessary variables are set
# =============================================================================

if [[ ! -f "$OXID_SOURCE_PATH/bootstrap.php" ]]; then
    echo "OXID bootstrap file not found on $OXID_SOURCE_PATH/bootstrap.php"
    exit 1
fi

if [[ -z $MYSQL_DATABASE_NAME ]]; then
    echo "MYSQL_DATABASE_NAME has not been specified"
    exit 2
fi

if [[ -z $MYSQL_USER ]]; then
    echo "MYSQL_USER has not been specified"
    exit 3
fi

# =============================================================================
# Setup MySQL database
# =============================================================================

if [[ -f "$OXID_SOURCE_PATH/setup/sql/database_schema.sql" ]]; then
    DATABASE_FILE_NAME="database_schema.sql"
elif [[ -f "$OXID_SOURCE_PATH/setup/sql/database.sql" ]]; then
    DATABASE_FILE_NAME="database.sql"
else
    echo "Initial database schema file was not found"
    exit 4
fi

mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD -e "DROP DATABASE IF EXISTS $MYSQL_DATABASE_NAME"
mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE_NAME"
mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE_NAME < $OXID_SOURCE_PATH/setup/sql/$DATABASE_FILE_NAME
mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE_NAME < $OXID_SOURCE_PATH/setup/sql/latin1_to_utf8.sql


# =============================================================================
# Replace configuration values in config.inc.php
#
# Credits: https://github.com/OXID-eSales/oxideshop_ce/blob/v4.9.4/.travis.yml#L43
# =============================================================================

sed -i 's|<dbHost_ce>|127.0.0.1|; s|<dbName_ce>|'$MYSQL_DATABASE_NAME'|; s|<dbUser_ce>|'$MYSQL_USER'|; s|<dbPwd_ce>|'$MYSQL_PASSWORD'|; s|<sShopURL_ce>|http://127.0.0.1|; s|<sShopDir_ce>|'$OXID_SOURCE_PATH'|; s|<sCompileDir_ce>|'$OXID_SOURCE_PATH'/tmp|; s|<iUtfMode>|1|' oxid/config.inc.php
